using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

using Microsoft.AspNetCore.Identity;

using Bie.Business.Enums;
using Bie.Business.ValueObjects;

namespace Bie.Business.Models;

public class ApplicationUser : IdentityUser<Guid>
{
    public ApplicationUser()
    {
        FirstName = "";
        LastName = "";
    }

    public ApplicationUser(DateOnly birthDate, string? CPF, string firstName, string lastName, StatusEnum status = StatusEnum.Active)
    {
        BirthDate = birthDate;
        this.CPF = CPF;
        FirstName = firstName;
        LastName = lastName;
        Status = status;
        AutoGeneratedImage = false;
    }

    [Required]
    public DateOnly BirthDate { get; private set; }
    public string? CPF { get; private set; }
    public string FirstName { get; private set; }
    public string LastName { get; private set; }
    [DefaultValue(StatusEnum.Active)]
    public StatusEnum Status { get; private set; }
    public bool AutoGeneratedImage { get; private set; }
    public string? ImageUrl { get; private set; }
    public string? ImagePrompt { get; private set; }
    [NotMapped]
    public Base64? ImageBase64 { get; private set; }
    [NotMapped]
    public string ConfirmPassword { get; private set; } = string.Empty;
    public IList<Scheduling>? Schedulings { get; private set; }
    public IList<CompanyEmployee>? UserCompanies { get; private set; }
    [NotMapped]
    public IList<Company>? Companies { get; private set; }
    public List<EmployeeService>? Services { get; private set; }

    public void ChangeUserInfo(string firstName, string lastName, DateOnly birthDate, string? phone = null)
    {
        FirstName = firstName;
        LastName = lastName;
        BirthDate = birthDate;
        PhoneNumber = phone;
    }
}