using System.ComponentModel.DataAnnotations;

namespace Bie.Business.Models.Base;
public abstract class ProfileBase : EntityBase
{
    [Required]
    public string Name { get; set; } = string.Empty;
    [Required]
    public string Email { get; set; } = string.Empty;
    public string CityId { get; set; } = string.Empty;
    public City City { get; set; } = new();
    public string Address { get; set; } = string.Empty;
    public string AddressNumber { get; set; } = string.Empty;
    public string PostalCode { get; set; } = string.Empty;
    public string ImageUrl { get; set; } = string.Empty;
    public bool AutoGeneratedImage { get; set; }
    public string ImagePrompt { get; set; } = string.Empty;
    public string ImageBase64 { get; set; } = string.Empty;

    public IList<Scheduling> Schedulings { get; set; } = new List<Scheduling>();
}