using Bie.Business.Enums;
using Bie.Business.Models;
using Bie.Api.DTOs.Base;

using System.ComponentModel.DataAnnotations;

namespace Bie.Api.DTOs.Request;
public class CompanyRequestDto : BaseDto
{
    [Display(Name = "Name")]
    [Required(ErrorMessage = "Name is required")]
    public string Name { get; set; } = string.Empty;
    [Display(Name = "Email")]
    [EmailAddress]
    public string Email { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    [Display(Name = "CNPJ")]
    public string? Cnpj { get; set; }
    [Display(Name = "Auto Generate my Image Logo using AI")]
    public bool AutoGeneratedImage { get; set; }
    [Display(Name = "City")]
    public int? CityId { get; set; }
    public string? Address { get; set; } 
    [Display(Name = "Number")]
    public string? AddressNumber { get; set; }
    public string? PostalCode { get; set; }
    [Display(Name = "Is not a physical location")]
    public bool IsVirtual { get; set; }
    public string? ImageUrl { get; set; }
    public ScheduleStatusEnum ScheduleStatus { get; set; }


    // [Display(Name = "Services Offered")]
    // public List<SelectListItem> CategoriesSelectIds { get; set; } = LoadCategories();
    public List<CompanyOpeningHours> OpeningHours { get; set; } = LoadDefaultOpeningHours();
    public List<CompanyServiceOffered> ServicesOffered { get; set; } = new List<CompanyServiceOffered>();



    // private static List<SelectListItem> LoadCategories()
    // {
    //     List<SelectListItem> categories = new List<SelectListItem>();

    //     Enum.GetValues(typeof(CategoryEnum)).Cast<CategoryEnum>().ToList().ForEach(category => categories.Add(
    //         new SelectListItem(text: category.ToString(), value: ((int)category).ToString())));

    //     return categories;
    // }
    public static List<CompanyOpeningHours> LoadDefaultOpeningHours()
    {
        List<CompanyOpeningHours> defaultOpeningHours = [];

        Enum.GetValues(typeof(DayOfWeek)).Cast<DayOfWeek>().ToList().ForEach(dayOfWeek => defaultOpeningHours.Add(
            new CompanyOpeningHours
            {
                DayOfWeek = dayOfWeek,
                OpeningHour = new TimeSpan(9, 0, 0),
                ClosingHour = new TimeSpan(18, 0, 0)
            }));

        return defaultOpeningHours;
    }
}