using Bie.Business.Enums;
using Bie.Api.DTOs.Base;

using System.ComponentModel.DataAnnotations;

namespace Bie.Api.DTOs.Request;
public class CompanyRequestDto : BaseDto
{
    [Display(Name = "Name")]
    [Required(ErrorMessage = "Name is required")]
    public string Name { get; set; } = string.Empty;
    [Display(Name = "Email")]
    [EmailAddress]
    public string Email { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    [Display(Name = "CNPJ")]
    public string? Cnpj { get; set; }
    [Display(Name = "Auto Generate my Image Logo using AI")]
    public bool AutoGeneratedImage { get; set; }
    [Display(Name = "City")]
    public int? CityId { get; set; }
    public string? Address { get; set; } 
    [Display(Name = "Number")]
    public string? AddressNumber { get; set; }
    public string? PostalCode { get; set; }
    [Display(Name = "Is not a physical location")]
    public bool IsVirtual { get; set; }
    public string? ImageUrl { get; set; }
    public ScheduleStatusEnum ScheduleStatus { get; set; }

    public List<CompanyOpeningHoursRequestDto> OpeningHours { get; set; } = [];
    public List<CompanyServiceOfferedRequestDto> ServicesOffered { get; set; } = [];
    public List<CompanyEmployeeRequestDto> Employees { get; set; } = [];
}